name = "black-betty"
main = "src/index.ts"
compatibility_date = "2025-06-29"

[vars]
TELEGRAM_BOT_TOKEN = "${TELEGRAM_BOT_TOKEN}"
ALLOWED_USER_IDS = "${ALLOWED_USER_IDS}"
WEBHOOK_SECRET = "${WEBHOOK_SECRET}"

[observability]
enabled = true
head_sampling_rate = 1
