name: Continuous Deployment (CD)

on:
  workflow_dispatch:

jobs:

  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    permissions: write-all
    with:
      release: true

  release:
    needs: build
    uses: ./.github/workflows/release.yml
    secrets: inherit
    permissions: write-all


  deploy:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    permissions: write-all