name: Deploy

on:
  workflow_call:


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24.2.0'

      - name: Install dependencies
        run: npm install

      - name: Deploy
        run: npm run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}

      

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: worker.js
          path: worker.js
          retention-days: 1
  